# keybinds to apply across different apps
# for example, vi keybinds are applied to vim, emacs,
# and qutebrowser

[vi]
left           = "h"
down           = "n"
up             = "e"
right          = "i"
jump-exclusive = "t" # TODO rotate t/f/j
jump-inclusive = "j"
jump-next      = "."
jump-prev      = ","
word-next      = "w"
word-end       = "f"
word-back      = "b"
insert         = "u"
undo           = "l"
search         = "/"
search-next    = "k" # search-prev is capitalized
